print(5+5)
print(10-5)
print(10/3)
print(10//3)
print(isinstance(10.0,int))
print(2*3)
print(2**3)
print('arsh'+'iya')
print("abc"*5)
print("arsh"  "iya")
print(1==2)
print(1!=2 )
print(1<2)
print(2>3)
print('ab'<'c')
print('a'<'A')
print(True and False)
print(True or False)
print(True and 1)
print(1 and 0)
print(1 and 5)
print(isinstance(True,int))
print(type(True))
print(bool(1))
#true or b = true
#false or b = b
#true and b = b
#false and b = false
#a or b = a(if a is truthy)
#a or b = b(if a is falsey)
#a and b = b(if a is truthy)
#a and b = a(if a is falsey)
print('arshiya'and '6')
print(''and 6)
print(''or 2.5)
print(bool(''))
print(bool({1,2,3}))
print(''and 0)
